### ISSUE TITLE
Connection to MQTT broker

### ISSUE THREAD

**Issue by nightshadow931** [lafe/Teams2Mqtt#1]
Hi,

I'm trying to get this thing to work, and I could use some help. :)
I installed MQTT broker on my HA instance, downloaded your app on my windows laptop and did everything as per instructions from the PowerShell. All went fine, no errors reported.
I've tested mqtt broker addon and it works fine.
This is my appsettings.json:
```
{
  "$schema": "./appsettings.schema.json",

  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.Hosting.Lifetime": "Information"
    },
    "EventLog": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    }
  },
  "configuration": {
    "teamsApiKey": "api-key-here"
  },
  "mqtt": {
    "server": "192.168.1.17",
    "port": 1883,
	"username": "homeassistant",
	"password": "Cha7nair5bi1eethah9AipedochiF3voh8ev9NahCheiphohgheihaegahneequ6",
    "homeAssistantAutodiscoveryTopic": "homeassistant",
    "deviceSuggestedArea": "Device",
    "removeDevicesOnShutdown": false
  },
  "sensorLocalizations": [
    {
      "sensorId": "isMuted",
      "sensorName": "Is Muted"
    },
    {
      "sensorId": "isCameraOn",
      "sensorName": "Is Camera On"
    },
    {
      "sensorId": "isHandRaised",
      "sensorName": "Is Hand Raised"
    },
    {
      "sensorId": "isInMeeting",
      "sensorName": "Is In Meeting"
    },
    {
      "sensorId": "isRecordingOn",
      "sensorName": "Is Recording On"
    },
    {
      "sensorId": "isBackgroundBlurred",
      "sensorName": "Is Background Blurred"
    }
  ]
}
```

192.168.1.17 is the address of my HA instance. Username and password are from the MQTT integrations page:
![image](https://github.com/lafe/Teams2Mqtt/assets/10613880/c4fbd4c8-fcab-43fa-a00e-b2c133c9a4d9)

However, nothing is coming to my HA through MQTT addon. I don't see anything in the log, and I don't see any messages from the MQTT integrations page. My Teams is up and running on my laptop.
I found this error in the event viewer:
```
Category: lafe.Teams2Mqtt.Services.TeamsCommunication
EventId: 1216
TeamsCommunication:ConnectAsync

An error occurred while processing web socket messages: System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAtLeastAsyncCore(Memory`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at lafe.Teams2Mqtt.Services.TeamsCommunication.WebSocketListener() in /home/runner/work/Teams2Mqtt/Teams2Mqtt/Teams2Mqtt/Services/TeamsCommunication.cs:line 160
```

That's the only 'error' message I can see, there are a bunch of other 'Information' messages.
Any idea what I'm doing wrong? Is my config ok?

**Comment by lafe** [comment]
The error message looks like a connection problem to the Teams API. If the application does not get a connection to Teams, this is the resulting error message.

For problem solving/troubleshooting:

- You set the Teams API-Key, correct? Your configuration only shows "api-key-here", so I want to make sure. 
- Currently, the app also only works with the "legacy" client. The new one, which is currently in beta, does not support 3rd party apps at the moment. 
- I also have the impression that the "legacy" client became somewhat flaky in the last few months and the application (as well as my Stream Deck) do not get the current state. This is most often solved by a restart of Teams or your PC. Sometimes it also works to disable the 3rd party integration slider in Teams and then reactivate it again.

I hope one of these approaches works.

**Comment by nightshadow931** [comment]
Thank you for your fast response.

- Correct, I did insert my teams API key in configuration
- I don't think I'm using the beta version, should be the legacy one -> You have Microsoft Teams Version 1.6.00.20074 (64-bit). It was last updated on 4.8.2023..

Anyway, it looks like it works now after the restart.. so seems you're right, client is somewhat flaky
